export const CONFIG = {
  languages: {
    en: 'English',
    hi: 'Hindi',
    mr: 'Marathi',
  },
  speechCodes: {
    en: 'en-US',
    hi: 'hi-IN',
    mr: 'mr-IN',
  },
  maxHistory: 30,
  confidenceThreshold: 0.75,
  detectionInterval: 100,
};

export const WORD_TRANSLATIONS: Record<string, Record<string, string>> = {
  // Numbers
  '1':  { en: 'One',       hi: 'एक',      mr: 'एक'      },
  '2':  { en: 'Two',       hi: 'दो',       mr: 'दोन'     },
  '3':  { en: 'Three',     hi: 'तीन',      mr: 'तीन'     },
  '4':  { en: 'Four',      hi: 'चार',      mr: 'चार'     },
  '5':  { en: 'Five',      hi: 'पाँच',     mr: 'पाच'     },
  '6':  { en: 'Six',       hi: 'छह',       mr: 'सहा'     },
  '7':  { en: 'Seven',     hi: 'सात',      mr: 'सात'     },
  '8':  { en: 'Eight',     hi: 'आठ',       mr: 'आठ'      },
  '9':  { en: 'Nine',      hi: 'नौ',       mr: 'नऊ'      },
  '10': { en: 'Ten',       hi: 'दस',       mr: 'दहा'     },
  '11': { en: 'Eleven',    hi: 'ग्यारह',   mr: 'अकरा'    },
  '12': { en: 'Twelve',    hi: 'बारह',     mr: 'बारा'    },
  '13': { en: 'Thirteen',  hi: 'तेरह',     mr: 'तेरा'    },
  '14': { en: 'Fourteen',  hi: 'चौदह',     mr: 'चौदा'    },
  '15': { en: 'Fifteen',   hi: 'पंद्रह',   mr: 'पंधरा'   },
  '16': { en: 'Sixteen',   hi: 'सोलह',     mr: 'सोळा'    },
  '17': { en: 'Seventeen', hi: 'सत्रह',    mr: 'सतरा'    },
  '18': { en: 'Eighteen',  hi: 'अठारह',    mr: 'अठरा'    },
  '19': { en: 'Nineteen',  hi: 'उन्नीस',   mr: 'एकोणीस'  },
  '20': { en: 'Twenty',    hi: 'बीस',      mr: 'वीस'     },

  // Letters (shown as-is in all languages)
  A: { en: 'A', hi: 'A', mr: 'A' },
  B: { en: 'B', hi: 'B', mr: 'B' },
  C: { en: 'C', hi: 'C', mr: 'C' },
  D: { en: 'D', hi: 'D', mr: 'D' },
  E: { en: 'E', hi: 'E', mr: 'E' },
  F: { en: 'F', hi: 'F', mr: 'F' },
  G: { en: 'G', hi: 'G', mr: 'G' },
  H: { en: 'H', hi: 'H', mr: 'H' },
  I: { en: 'I', hi: 'I', mr: 'I' },
  J: { en: 'J', hi: 'J', mr: 'J' },
  K: { en: 'K', hi: 'K', mr: 'K' },
  L: { en: 'L', hi: 'L', mr: 'L' },
  M: { en: 'M', hi: 'M', mr: 'M' },
  N: { en: 'N', hi: 'N', mr: 'N' },
  O: { en: 'O', hi: 'O', mr: 'O' },
  P: { en: 'P', hi: 'P', mr: 'P' },
  Q: { en: 'Q', hi: 'Q', mr: 'Q' },
  R: { en: 'R', hi: 'R', mr: 'R' },
  S: { en: 'S', hi: 'S', mr: 'S' },
  T: { en: 'T', hi: 'T', mr: 'T' },
  U: { en: 'U', hi: 'U', mr: 'U' },
  V: { en: 'V', hi: 'V', mr: 'V' },
  W: { en: 'W', hi: 'W', mr: 'W' },
  X: { en: 'X', hi: 'X', mr: 'X' },
  Y: { en: 'Y', hi: 'Y', mr: 'Y' },
  Z: { en: 'Z', hi: 'Z', mr: 'Z' },

  // Daily life words
  Hello:    { en: 'Hello',     hi: 'नमस्ते',    mr: 'नमस्कार'  },
  Yes:      { en: 'Yes',       hi: 'हाँ',        mr: 'होय'      },
  No:       { en: 'No',        hi: 'नहीं',       mr: 'नाही'     },
  Good:     { en: 'Good',      hi: 'अच्छा',      mr: 'चांगले'   },
  Bad:      { en: 'Bad',       hi: 'बुरा',       mr: 'वाईट'     },
  Sorry:    { en: 'Sorry',     hi: 'माफ करें',   mr: 'माफ करा'  },
  Please:   { en: 'Please',    hi: 'कृपया',      mr: 'कृपया'    },
  Help:     { en: 'Help',      hi: 'मदद',        mr: 'मदत'      },
  Stop:     { en: 'Stop',      hi: 'रुको',       mr: 'थांबा'    },
  Water:    { en: 'Water',     hi: 'पानी',       mr: 'पाणी'     },
  Food:     { en: 'Food',      hi: 'खाना',       mr: 'अन्न'     },
  Home:     { en: 'Home',      hi: 'घर',         mr: 'घर'       },
  Love:     { en: 'Love',      hi: 'प्यार',      mr: 'प्रेम'    },
  Friend:   { en: 'Friend',    hi: 'दोस्त',      mr: 'मित्र'    },
  Family:   { en: 'Family',    hi: 'परिवार',     mr: 'कुटुंब'   },
  'Thank You': { en: 'Thank You', hi: 'धन्यवाद', mr: 'धन्यवाद'  },
  Morning:  { en: 'Morning',   hi: 'सुबह',       mr: 'सकाळ'     },
  Night:    { en: 'Night',     hi: 'रात',        mr: 'रात्र'    },
  School:   { en: 'School',    hi: 'स्कूल',      mr: 'शाळा'     },
  Work:     { en: 'Work',      hi: 'काम',        mr: 'काम'      },
  Sleep:    { en: 'Sleep',     hi: 'नींद',       mr: 'झोप'      },
  Sick:     { en: 'Sick',      hi: 'बीमार',      mr: 'आजारी'    },
  Happy:    { en: 'Happy',     hi: 'खुश',        mr: 'आनंदी'    },
  Sad:      { en: 'Sad',       hi: 'दुखी',       mr: 'दुःखी'    },
  Hungry:   { en: 'Hungry',    hi: 'भूखा',       mr: 'भुकेलेले' },
  Bathroom: { en: 'Bathroom',  hi: 'बाथरूम',     mr: 'बाथरूम'   },
  Doctor:   { en: 'Doctor',    hi: 'डॉक्टर',     mr: 'डॉक्टर'   },
  Mother:   { en: 'Mother',    hi: 'माँ',         mr: 'आई'       },
  Father:   { en: 'Father',    hi: 'पिता',       mr: 'बाबा'     },

  // Simple sentences
  'I love you':     { en: 'I love you',        hi: 'मैं तुमसे प्यार करता हूँ', mr: 'मी तुझ्यावर प्रेम करतो' },
  'Thank you':      { en: 'Thank you',         hi: 'धन्यवाद',                  mr: 'धन्यवाद'                 },
  'How are you?':   { en: 'How are you?',      hi: 'आप कैसे हैं?',             mr: 'तुम्ही कसे आहात?'        },
  'Good morning':   { en: 'Good morning',      hi: 'सुप्रभात',                 mr: 'शुभ सकाळ'                },
  'Good night':     { en: 'Good night',        hi: 'शुभ रात्रि',               mr: 'शुभ रात्री'              },
  'Please help me': { en: 'Please help me',    hi: 'कृपया मेरी मदद करें',      mr: 'कृपया मला मदत करा'       },
  'I am hungry':    { en: 'I am hungry',       hi: 'मुझे भूख लगी है',          mr: 'मला भूक लागली आहे'       },
  'I am happy':     { en: 'I am happy',        hi: 'मैं खुश हूँ',              mr: 'मी आनंदी आहे'            },
};

export type Language = 'en' | 'hi' | 'mr';